# Output generated by Claude.AI
# Prompt was: So using Seurat / R how would I go about using GSEA to do this test?
# "This test" refers to doing a rank based GSEA test like one does for 
# bulk RNASeq


library(Seurat)
library(SeuratData)
library(fgsea)  # Fast GSEA implementation
library(msigdbr)  # For gene sets
library(dplyr)
library(ggplot2)
library(DESeq2)

# get data for doing analysis
InstallData("ifnb")

LoadData("ifnb")
# Update old Seurat object to accommodate new features
ifnb <- UpdateSeuratObject(ifnb)


# get gene sets (Hallmark gene set)
# Get gene sets from MSigDB (e.g., Hallmark pathways)
gene_sets <- msigdbr(species = "Homo sapiens", category = "H")

# Convert to list format for fgsea
pathways <- gene_sets %>%
  split(x = .$gene_symbol, f = .$gs_name)

# Or use other categories:
# "C2" for curated gene sets
# "C5" for GO terms
# "C8" for cell type signatures

# first way to do it, use FindMarkers on a per cell basis
Idents(ifnb) <- "seurat_annotations"

ifnb_cd14 <- subset(ifnb, idents = "CD14 Mono")

Idents(ifnb_cd14) <- "stim"
table(Idents(ifnb_cd14))

markers <- FindMarkers(
  ifnb_cd14,
  ident.1 = "STIM",
  ident.2 = "CTRL",
  test.use = "wilcox",  # or "MAST", "DESeq2"
  logfc.threshold = 0,  # Get all genes
  min.pct = 0.1
)
markers$gene_name <- rownames(markers)

deseq_markers <- FindMarkers(
  ifnb_cd14,
  ident.1 = "STIM",
  ident.2 = "CTRL",
  test.use = "DESeq2",  # or "MAST", "DESeq2"
  logfc.threshold = 0,  # Get all genes
  min.pct = 0.1
)


# Create ranked gene list (by log fold change or stat)
# Important: remove NAs and sort
ranked_genes <- markers %>%
  filter(!is.na(avg_log2FC) &
           !is.infinite(avg_log2FC)) %>%
  arrange(desc(avg_log2FC)) %>%
  pull(avg_log2FC, name = gene_name)

fgsea_results <- fgsea(
  pathways = pathways,
  stats = ranked_genes,
  minSize = 15,
  maxSize = 500,
  nperm = 10000
)

fgsea_results %>%
  arrange(padj) %>%
  head(20)

# Plot enrichment for top pathway
plotEnrichment(
  pathways[["HALLMARK_INTERFERON_GAMMA_RESPONSE"]], 
  ranked_genes
) + labs(title = "IFN-γ Response")

# this is nice

# Table plot of top pathways
topPathways <- fgsea_results %>%
  filter(padj < 0.05) %>%
  arrange(desc(abs(NES))) %>%
  head(20) %>%
  pull(pathway)

plotGseaTable(
  pathways[topPathways],
  ranked_genes,
  fgsea_results,
  gseaParam = 0.5
)

# this is meh

# Pseudobulk analysis, featuring DESeq2

# aggregate cells to create "pseudobulk" 
aggregate_ifnb <- AggregateExpression(ifnb, group.by = c("seurat_annotations", "stim"), 
                                      return.seurat = TRUE)
Idents(aggregate_ifnb) <- "seurat_annotations"
agg_ifnb_cdmono <- subset(aggregate_ifnb, idents=c("CD14 Mono",
                                                   "CD16 Mono"))

# create metadata for samples
sample_metadata <- agg_ifnb_cdmono@meta.data %>%
  select(stim, seurat_annotations, orig.ident) %>%
  distinct() %>%
  as.data.frame()
rownames(sample_metadata) <- sample_metadata$orig.ident

dds <- DESeqDataSetFromMatrix(
  countData = agg_ifnb_cdmono[["RNA"]]$counts,
  colData = sample_metadata,
  design = ~ stim
)

dds <- DESeq(dds)
res <- results(dds, contrast = c("stim", "STIM", "CTRL"))

res <- as.data.frame(res)
res$gene_name <- rownames(res)

# Create ranked list
ranked_genes <- res %>%
  filter(!is.na(stat)) %>%
  arrange(desc(stat)) %>%
  pull(stat, name = gene_name)

fgsea_results <- fgsea(
  pathways = pathways,
  stats = ranked_genes,
  minSize = 15,
  maxSize = 500
)

# Plot enrichment for top pathway
plotEnrichment(
  pathways[["HALLMARK_INTERFERON_GAMMA_RESPONSE"]], 
  ranked_genes
) + labs(title = "IFN-γ Response")


plotEnrichment(
  pathways[["HALLMARK_INFLAMMATORY_RESPONSE"]], 
  ranked_genes
) + labs(title = "Inflammatory Response")

plotEnrichment(
  pathways[["HALLMARK_XENOBIOTIC_METABOLISM"]], 
  ranked_genes
) + labs(title = "Xenobiotic Metabolism")

